# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: snakemake
# in order of priority: highest (top) to lowest (bottom)
channels:
  - bioconda
  - conda-forge # libxml2 for windows
dependencies:
  - snakemake

