# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: libmysqlclient-6.1.6
# in order of priority: highest (top) to lowest (bottom)
channels:
#  - anaconda
#  - goodman # mysql-python for mac
  - bioconda
#  - cyclus # java-jdk for windows
#  - conda-forge # libxml2 for windows
#  - BjornFJohansson # wxpython for linux
dependencies:
#  - mysqlclient
#  - mysql-python
  - mysql-connector-c==6.1.6
